# Introduction to Deep Learning with PyTorch

In this notebook, you'll get introduced to [PyTorch](http://pytorch.org/), a framework for building and training neural networks. PyTorch in a lot of ways behaves like the arrays you love from Numpy. These Numpy arrays, after all, are just tensors. PyTorch takes these tensors and makes it simple to move them to GPUs for the faster processing needed when training neural networks. It also provides a module that automatically calculates gradients (for backpropagation!) and another module specifically for building neural networks. All together, PyTorch ends up being more coherent with Python and the Numpy/Scipy stack compared to TensorFlow and other frameworks.


## Neural Networks

Deep Learning is based on artificial neural networks which have been around in some form since the late 1950s. The networks are built from individual parts approximating neurons, typically called units or simply "neurons." Each unit has some number of weighted inputs. These weighted inputs are summed together (a linear combination) then passed through an activation function to get the unit's output.

<img src="assets/simple_neuron.png" width=400px>

Mathematically this looks like: 

$$
\begin{align}
y &= f(w_1 x_1 + w_2 x_2 + b) \\
y &= f\left(\sum_i w_i x_i +b \right)
\end{align}
$$

With vectors this is the dot/inner product of two vectors:

$$
h = \begin{bmatrix}
x_1 \, x_2 \cdots  x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_1 \\
           w_2 \\
           \vdots \\
           w_n
\end{bmatrix}
$$

## Tensors

It turns out neural network computations are just a bunch of linear algebra operations on *tensors*, a generalization of matrices. A vector is a 1-dimensional tensor, a matrix is a 2-dimensional tensor, an array with three indices is a 3-dimensional tensor (RGB color images for example). The fundamental data structure for neural networks are tensors and PyTorch (as well as pretty much every other deep learning framework) is built around tensors.

<img src="assets/tensor_examples.svg" width=600px>

With the basics covered, it's time to explore how we can use PyTorch to build a simple neural network.

In [1]:
import torch

In [2]:
#Just checking the torch version
print(torch.__version__)

1.0.0


### Activation Function

In [3]:
def activation(x):
    ''' Sigmoid Function
        Arguments => torch.tensor
        Used for probability coz its range is B/W 0 and 1'''
    return 1/(1 + torch.exp(x))

### Generating Data

In [4]:
torch.manual_seed(7)# Setting random seeds so things are predictable

#randn = Returns a tensor filled with random numbers from a normal distribution with mean `0` and variance `1` 
features = torch.randn((1,5)) # 1 row and 5 columns

#Weights again random normal variables
weights = torch.rand_like(features) # similar to randn but it takes another tensor as input

#Bias Term
bias = torch.randn((1,1))


Above I generated data we can use to get the output of our simple network. This is all just random for now, going forward we'll start using normal data. Going through each relevant line:

`features = torch.randn((1, 5))` creates a tensor with shape `(1, 5)`, one row and five columns, that contains values randomly distributed according to the normal distribution with a mean of zero and standard deviation of one. 

`weights = torch.randn_like(features)` creates another tensor with the same shape as `features`, again containing values from a normal distribution.

Finally, `bias = torch.randn((1, 1))` creates a single value from a normal distribution.

PyTorch tensors can be added, multiplied, subtracted, etc, just like Numpy arrays. In general, you'll use PyTorch tensors pretty much the same way you'd use Numpy arrays. They come with some nice benefits though such as GPU acceleration which we'll get to later

In [5]:
features , weights , bias

(tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]]),
 tensor([[0.2868, 0.2063, 0.4451, 0.3593, 0.7204]]),
 tensor([[-0.8948]]))

In [6]:
features.shape , weights.shape , bias.shape

(torch.Size([1, 5]), torch.Size([1, 5]), torch.Size([1, 1]))

# Exercise 1
> Calculate the output of the network with input features `features`, weights `weights`, and bias `bias`. Similar to Numpy, PyTorch has a [`torch.sum()`](https://pytorch.org/docs/stable/torch.html#torch.sum) function, as well as a `.sum()` method on tensors, for taking sums. Use the function `activation` defined above as the activation function

In [7]:
# y = activation-Function ( summation(wi*xi) + b )
summation = torch.sum(features * weights)
addingBias = summation + bias
output1 = activation(addingBias)

'''OR'''

output2 = activation((features * weights).sum() + bias)

In [8]:
output1 , output2

(tensor([[0.3860]]), tensor([[0.3860]]))

You can do the multiplication and sum in the same operation using a matrix multiplication. In general, you'll want to use matrix multiplications since they are more efficient and accelerated using modern libraries and high-performance computing on GPUs.

Here, we want to do a matrix multiplication of the features and the weights. For this we can use [`torch.mm()`](https://pytorch.org/docs/stable/torch.html#torch.mm) or [`torch.matmul()`](https://pytorch.org/docs/stable/torch.html#torch.matmul) which is somewhat more complicated and supports broadcasting. If we try to do it with `features` and `weights` as they are, we'll get an error

```python
>> torch.mm(features, weights)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-15d592eb5279> in <module>()
----> 1 torch.mm(features, weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at /Users/soumith/minicondabuild3/conda-bld/pytorch_1524590658547/work/aten/src/TH/generic/THTensorMath.c:2033
```

As you're building neural networks in any framework, you'll see this often. Really often. What's happening here is our tensors aren't the correct shapes to perform a matrix multiplication. Remember that for matrix multiplications, the number of columns in the first tensor must equal to the number of rows in the second column. Both `features` and `weights` have the same shape, `(1, 5)`. This means we need to change the shape of `weights` to get the matrix multiplication to work.

**Note:** To see the shape of a tensor called `tensor`, use `tensor.shape`. If you're building neural networks, you'll be using this method often.

There are a few options here: [`weights.reshape()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.reshape), [`weights.resize_()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.resize_), and [`weights.view()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view).

* `weights.reshape(a, b)` will return a new tensor with the same data as `weights` with size `(a, b)` sometimes, and sometimes a clone, as in it copies the data to another part of memory.
* `weights.resize_(a, b)` returns the same tensor with a different shape. However, if the new shape results in fewer elements than the original tensor, some elements will be removed from the tensor (but not from memory). If the new shape results in more elements than the original tensor, new elements will be uninitialized in memory. Here I should note that the underscore at the end of the method denotes that this method is performed **in-place**. Here is a great forum thread to [read more about in-place operations](https://discuss.pytorch.org/t/what-is-in-place-operation/16244) in PyTorch.
* `weights.view(a, b)` will return a new tensor with the same data as `weights` with size `(a, b)`.

I usually use `.view()`, but any of the three methods will work for this. So, now we can reshape `weights` to have five rows and one column with something like `weights.view(5, 1)`.


# Exercise 2
> Calculate the output of our little network using matrix multiplication.

In [9]:
output3 = activation(torch.mm(features , weights.view(5,1)) + bias)

In [10]:
output3

tensor([[0.3860]])

### Stack them up!

That's how you can calculate the output for a single neuron. The real power of this algorithm happens when you start stacking these individual units into layers and stacks of layers, into a network of neurons. The output of one layer of neurons becomes the input for the next layer. With multiple input units and output units, we now need to express the weights as a matrix.

<img src='assets/multilayer_diagram_weights.png' width=450px>

The first layer shown on the bottom here are the inputs, understandably called the **input layer**. The middle layer is called the **hidden layer**, and the final layer (on the right) is the **output layer**. We can express this network mathematically with matrices again and use matrix multiplication to get linear combinations for each unit in one operation. For example, the hidden layer ($h_1$ and $h_2$ here) can be calculated 

$$
\vec{h} = [h_1 \, h_2] = 
\begin{bmatrix}
x_1 \, x_2 \cdots \, x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_{11} & w_{12} \\
           w_{21} &w_{22} \\
           \vdots &\vdots \\
           w_{n1} &w_{n2}
\end{bmatrix}
$$

The output for this small network is found by treating the hidden layer as inputs for the output unit. The network output is expressed simply

$$
y =  f_2 \! \left(\, f_1 \! \left(\vec{x} \, \mathbf{W_1}\right) \mathbf{W_2} \right)
$$

In [11]:
torch.manual_seed(7)

# Input features
features = torch.randn((1,3))

# Size of each layer
nInput = features.shape[1] #i.e 3
nHidden = 2 
nOutput = 1

# Weights
w1 = torch.randn(nInput , nHidden)

w2 = torch.randn(nHidden , nOutput)

#Bias Terms
b1 = torch.randn((1 , nHidden))

b2 = torch.randn((1 , nOutput))

# Exercise 3
> Calculate the output for this multi-layer network using the weights `W1` & `W2`, and the biases, `B1` & `B2`. 

In [12]:
features.shape , w1.shape , w2.shape , 

(torch.Size([1, 3]), torch.Size([3, 2]), torch.Size([2, 1]))

In [13]:
h = activation(torch.mm(features , w1) + b1)
output4 = activation(torch.mm(h , w2) + b2)

In [14]:
output4

tensor([[0.5290]])

The number of hidden units a parameter of the network, often called a **hyperparameter** to differentiate it from the weights and biases parameters. As you'll see later when we discuss training a neural network, the more hidden units a network has, and the more layers, the better able it is to learn from data and make accurate predictions.

## Numpy to Torch and back

Special bonus section! PyTorch has a great feature for converting between Numpy arrays and Torch tensors. To create a tensor from a Numpy array, use `torch.from_numpy()`. To convert a tensor to a Numpy array, use the `.numpy()` method.

In [15]:
import numpy as np

In [16]:
a = np.random.rand(4,3)
a

array([[8.92633223e-01, 4.25618552e-02, 4.93313852e-01],
       [4.46273393e-02, 4.69556733e-01, 9.82909903e-01],
       [6.20569415e-04, 4.39514289e-01, 8.15604928e-01],
       [6.68553627e-01, 4.79176350e-01, 2.65471256e-01]])

In [17]:
b = torch.from_numpy(a)
b

tensor([[8.9263e-01, 4.2562e-02, 4.9331e-01],
        [4.4627e-02, 4.6956e-01, 9.8291e-01],
        [6.2057e-04, 4.3951e-01, 8.1560e-01],
        [6.6855e-01, 4.7918e-01, 2.6547e-01]], dtype=torch.float64)

In [18]:
b.numpy()

array([[8.92633223e-01, 4.25618552e-02, 4.93313852e-01],
       [4.46273393e-02, 4.69556733e-01, 9.82909903e-01],
       [6.20569415e-04, 4.39514289e-01, 8.15604928e-01],
       [6.68553627e-01, 4.79176350e-01, 2.65471256e-01]])

* The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object,the other will change as well.
# _ is for inplace operations

In [19]:
b.mul_(2)

tensor([[1.7853e+00, 8.5124e-02, 9.8663e-01],
        [8.9255e-02, 9.3911e-01, 1.9658e+00],
        [1.2411e-03, 8.7903e-01, 1.6312e+00],
        [1.3371e+00, 9.5835e-01, 5.3094e-01]], dtype=torch.float64)

 Lets see if our numpy array has also changed or not

In [20]:
a

array([[1.78526645e+00, 8.51237105e-02, 9.86627704e-01],
       [8.92546786e-02, 9.39113465e-01, 1.96581981e+00],
       [1.24113883e-03, 8.79028577e-01, 1.63120986e+00],
       [1.33710725e+00, 9.58352700e-01, 5.30942512e-01]])

# Cheers!