## Lesson: Toy Differential Privacy - Simple Database Queries

In this section we're going to play around with Differential Privacy in the context of a database query. The database is going to be a VERY simple database with only one boolean column. Each row corresponds to a person. Each value corresponds to whether or not that person has a certain private attribute (such as whether they have a certain disease, or whether they are above/below a certain age). We are then going to learn how to know whether a database query over such a small database is differentially private or not - and more importantly - what techniques are at our disposal to ensure various levels of privacy


### First We Create a Simple Database

Step one is to create our database - we're going to do this by initializing a random list of 1s and 0s (which are the entries in our database). Note - the number of entries directly corresponds to the number of people in our database.

In [1]:
import torch

In [2]:
numberOfEntries = 5000
db = torch.rand(numberOfEntries)>0.5
len(db) , db

(5000, tensor([1, 1, 1,  ..., 1, 0, 0], dtype=torch.uint8))

## Project: Generate Parallel Databases

Key to the definition of differenital privacy is the ability to ask the question "When querying a database, if I removed someone from the database, would the output of the query be any different?". Thus, in order to check this, we must construct what we term "parallel databases" which are simply databases with one entry removed. 

In this first project, I want you to create a list of every parallel database to the one currently contained in the "db" variable. Then, I want you to create a function which both:

- creates the initial database (db)
- creates all parallel databases

In [3]:
type(db)

torch.Tensor

In [4]:
def getParallelDB(db , removeIndex):
    return(torch.cat((db[:removeIndex] , db[removeIndex+1:])))

In [5]:
def getParallelDatabases(db):
    parallelDatabases = []
    for i in range(len(db)):
        pdb = getParallelDB(db , i)
        parallelDatabases.append(pdb)
    
    return parallelDatabases

In [6]:
pdbs = getParallelDatabases(db)

In [7]:
len(pdbs)

5000

In [8]:
#pdbs

### Lets combine both the functions

In [9]:
def get_createDB_and_parallels(numOfEntries):
    db = torch.rand(numOfEntries)>0.5
    pdbs = getParallelDatabases(db)
    return(db , pdbs)

In [10]:
db , pdbs = get_createDB_and_parallels(20)

In [11]:
db

tensor([1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       dtype=torch.uint8)

In [12]:
pdbs

[tensor([1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,